# Generated by Django 5.1.5 on 2025-01-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        help_text="Please enter your email address", max_length=254
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        help_text="Please enter your skills", max_length=500
                    ),
                ),
                (
                    "workexp",
                    models.CharField(
                        help_text="Please enter your work experience", max_length=2000
                    ),
                ),
            ],
        ),
    ]
