# Generated by Django 5.1.5 on 2025-01-28 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logger",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 28, 4, 34, 52, 581033)
            ),
        ),
    ]
